TEMP C =                         
SELECT A.日结日期,                         
       A.首次到店时间,                         
       A.门店名称,                         
       A.门店代码,                                   
       A.商品名称,                         
       A.商品代码,                               
       A.大类名称,                         
       A.中类名称,                         
       A.小类名称,                         
       A.细类名称,                         
       A.实收金额,                         
       A.数量,                               
       B.仓库代码,                         
       B.仓库名称,                         
       B.仓库GID                         
FROM 合并(日*商品*门店)-销售信息表 A                   
LEFT JOIN 门店信息表_国内 B ON A.门店名称=B.门店名称                  
where 日结日期 IS NOT NULL                            
  AND [大类名称] IN ('健康美容',                            
                 '创意家居',                            
                 '季节性产品',                            
                 '数码配饰',                            
                 '文具/礼品',                            
                 '生活百货',                            
                 '精品包饰',                            
                 '食品类',                            
                 '饰品系列')                  
AND (DAY(LAST_DAY_OF_MONTH(YEAR(日结日期),MONTH(日结日期)))=31                            
       AND DAY(日结日期)>1)                            
  OR (DAY(LAST_DAY_OF_MONTH(YEAR(日结日期),MONTH(日结日期)))<1)
TEMP D =                      
SELECT FIRST_DAY_OF_MONTH(YEAR(ADD_MONTHS(日结日期,1)),MONTH(ADD_MONTHS(日结日期,1))) AS 填单时间,                      
       商品名称,                      
       商品代码,                               
       大类名称,                      
       中类名称,                      
       小类名称,                      
       细类名称,                      
       仓库代码,                      
       仓库名称,                      
       仓库GID,                      
       SUM(实收金额) AS 销售总金额,                      
       SUM(数量) AS 销售总数量                      
FROM C                      
GROUP BY FIRST_DAY_OF_MONTH(YEAR(ADD_MONTHS(日结日期,1)),MONTH(ADD_MONTHS(日结日期,1))),                  
         商品名称,                      
         商品代码,                        
         大类名称,                      
         中类名称,                      
         小类名称,                      
         细类名称,                      
         仓库代码,                      
         仓库名称,                      
         仓库GID
TEMP D1 = SELECT 填单时间,                      
       商品名称,                      
       商品代码,                               
       大类名称,                      
       中类名称,                      
       小类名称,                      
       细类名称,                      
       仓库代码,                      
       仓库名称,                      
       仓库GID,                      
       销售总金额,                      
       销售总数量,    
       RANK() OVER(PARTITION BY YEAR([填单时间]),MONTH([填单时间]),[仓库名称] ORDER BY [销售总数量] DESC) AS 销售数量排序,    
       RANK() OVER(PARTITION BY YEAR([填单时间]),MONTH([填单时间]),[仓库名称] ORDER BY [销售总金额] DESC) AS 销售金额排序    
FROM D
TEMP D2 = SELECT 填单时间,                      
       商品名称,                      
       商品代码,                               
       大类名称,                      
       中类名称,                      
       小类名称,                      
       细类名称,                      
       仓库代码,                      
       仓库名称,                      
       仓库GID,                      
       销售总金额,                      
       销售总数量,    
       销售数量排序,    
       销售金额排序,   
([销售数量排序]*0.6+[销售金额排序]*0.4) AS 得分   
FROM D1
TEMP D3 = SELECT 填单时间,                      
       商品名称,                      
       商品代码,                               
       大类名称,                      
       中类名称,                      
       小类名称,                      
       细类名称,                      
       仓库代码,                      
       仓库名称,                      
       仓库GID,                      
       销售总金额,                      
       销售总数量,    
       销售数量排序,    
       销售金额排序,   
       得分,   
       RANK() OVER(PARTITION BY YEAR([填单时间]),MONTH([填单时间]),[仓库名称] ORDER BY [得分]) AS 得分排序   
FROM D2
TEMP D4 = SELECT 填单时间,                      
       商品名称,                      
       商品代码,                               
       大类名称,                      
       中类名称,                      
       小类名称,                      
       细类名称,                      
       仓库代码,                      
       仓库名称,                      
       仓库GID,                      
       销售总金额,                      
       销售总数量,    
       销售数量排序,    
       销售金额排序,   
       得分,   
       得分排序   
FROM D3 WHERE 得分排序<=300